# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-pyth
name: Build Windows EXE

on:
  push:
    branches: [ "main", "dev" ]
  workflow_dispatch:      # Allows you to run this manually from the Actions tab

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Change to your preferred version

    - name: Install Dependencies
      run: |
        pip install pyinstaller
        if (Test-Path requirements.txt) { pip install -r requirements.txt }

    - name: Build EXE
      # Replace 'your_script.py' with your actual filename
      run: pyinstaller --onefile --noconsole proctoring_app.py

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: dist/*.exe
